export enum ERROR {
  PHONE_EXISTED = "PHONE_EXISTED",
  EMAIL_EXISTED = "EMAIL_EXISTED",
  PHONE_NOT_FOUND = "PHONE_NOT_FOUND",
  EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  CREATE_FAILED = "CREATE_FAILED",
  UPDATE_FAILED = "UPDATE_FAILED",
  DELETE_FAILED = "DELETE_FAILED",
  NOT_FOUND = "NOT_FOUND",
  SYSTEM_OCCURRENCE = "SYSTEM_OCCURRENCE",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
