export enum MESSAGE {
  REGISTER_SUCCESS = "Register success",
  REGISTER_FAILURE = "Register failure",
  PHONE_VERIFIED = "Phone number verified successfully",
  PHONE_USE_OLD_DEVICE = "The old device",
  PHONE_USE_ANOTHER_DEVICE = "the another device",
  SIGNIN_SUCCESS = "Sign in successfully",
  DELETE_SUCCESS = "Delete successfully",
  CREATE_SUCCESS = "Create successfully",
  UPDATE_SUCCESS = "Update successfully",
  DELETE_FAILED = "Delete failed",
  CREATE_FAILED = "Create failed",
  UPDATE_FAILED = "Update failed",
  LIST_SUCCESS = "List successfully",
  LIST_FAILED = "List failed",
  SUCCESS = "Thành công",
  INTERNAL_SERVER_ERROR = "Lỗi hệ thống!",
}
