const RIGHTS = {
    Super: {
        Code: 0,
        Name: 'super',
        Module: 'super',
        Title: 'super',
        Description: 'super_right',
    },
    Basic: {
        Code: 1,
        Name: 'basic',
        Module: 'basic',
        Title: 'basic',
        Description: 'basic_right',
    },
    CreateAdminUser: {
        Code: 2,
        Name: 'create_admin_user',
        Module: 'admin_user',
        Title: 'Tạo user',
        Description: 'create_admin_user',
        App: 'lottery',
    },
    EditAdminUser: {
        Code: 3,
        Name: 'edit_admin_user',
        Module: 'admin_user',
        Title: 'Edit user',
        Description: 'edit_admin_user',
        App: 'lottery',
    },
    DeleteAdminUser: {
        Code: 4,
        Name: 'delete_admin_user',
        Module: 'admin_user',
        Title: 'Xoá user',
        Description: 'delete_admin_user',
        App: 'lottery',
    },
    ShowListAdminUser: {
        Code: 5,
        Name: 'show_list_admin_user',
        Module: 'admin_user',
        Title: 'Show users',
        Description: 'show_list_admin_user',
        App: 'lottery',
    },
    SearchListAdminUser: {
        Code: 6,
        Name: 'search_list_admin_user',
        Module: 'admin_user',
        Title: 'Search users',
        Description: 'search_list_admin_user',
        App: 'lottery',
    },
    // report orders by book marker
    ShowReportOrdersByBookmarker: {
        Code: 7,
        Name: 'show_report_orders_by_bookmarker',
        Module: 'report_orders_by_bookmarker',
        Title: 'Show orders by bookmarker',
        Description: 'show_report_orders_by_bookmarker',
        App: 'lottery',
    },
    SearchReportOrdersByBookmarker: {
        Code: 8,
        Name: 'search_report_orders_by_bookmarker',
        Module: 'report_orders_by_bookmarker',
        Title: 'Search orders by bookmarker',
        Description: 'search_report_orders_by_bookmarker',
        App: 'lottery',
    },
    ExportExcelReportOrdersByBookmarker: {
        Code: 9,
        Name: 'export_excel_report_orders_by_bookmarker',
        Module: 'report_orders_by_bookmarker',
        Title: 'Export excel orders',
        Description: 'export_excel_report_orders_by_bookmarker',
        App: 'lottery',
    },
    // report orders by game
    ShowReportOrdersByGame: {
        Code: 10,
        Name: 'show_report_orders_by_game',
        Module: 'report_orders_by_game',
        Title: 'Show orders by game',
        Description: 'show_report_orders_by_game',
        App: 'lottery',
    },
    SearchReportOrdersByGame: {
        Code: 11,
        Name: 'search_report_orders_by_game',
        Module: 'report_orders_by_game',
        Title: 'Search orders by game',
        Description: 'search_report_orders_by_game',
        App: 'lottery',
    },
    ExportExcelReportOrdersByGame: {
        Code: 12,
        Name: 'export_excel_report_orders_by_game',
        Module: 'report_orders_by_game',
        Title: 'Export excel orders',
        Description: 'export_excel_report_orders_by_game',
        App: 'lottery',
    },
    // report orders by user
    ShowReportOrdersByUser: {
        Code: 13,
        Name: 'show_report_orders_by_user',
        Module: 'report_orders_by_user',
        Title: 'Show orders by user',
        Description: 'show_report_orders_by_user',
        App: 'lottery',
    },
    SearchReportOrdersByUser: {
        Code: 14,
        Name: 'search_report_orders_by_user',
        Module: 'report_orders_by_user',
        Title: 'Search orders by user',
        Description: 'search_report_orders_by_user',
        App: 'lottery',
    },
    ExportExcelReportOrdersByUser: {
        Code: 15,
        Name: 'export_excel_report_orders_by_user',
        Module: 'report_orders_by_user',
        Title: 'Export excel orders',
        Description: 'export_excel_report_orders_by_user',
        App: 'lottery',
    },
    // report orders
    ShowReportOrders: {
        Code: 16,
        Name: 'show_report_by_orders',
        Module: 'report_by_orders',
        Title: 'Show orders',
        Description: 'show_report_by_orders',
        App: 'lottery',
    },
    SearchReportOrders: {
        Code: 17,
        Name: 'search_report_orders',
        Module: 'report_by_orders',
        Title: 'Search orders',
        Description: 'search_report_orders',
        App: 'lottery',
    },
    ExportExcelReportOrders: {
        Code: 18,
        Name: 'export_excel_report_orders',
        Module: 'report_by_orders',
        Title: 'Export excel orders',
        Description: 'export_excel_report_orders',
        App: 'lottery',
    },
};

const RIGHTS_DEFAULT = ['basic'];

export {
    RIGHTS,
    RIGHTS_DEFAULT,
};