export enum ConectEnum {
  LOGIN = "LOGIN",
  UPDATE = "UPDATE",
  PAYMENT_FAKE = "PAYMENT_FAKE",
  PAYMENT_AUTH = "PAYMENT_AUTH",
  GET_INFO_FAKE = "GET_INFO_FAKE",
  GET_INFO_AUTH = "GET_INFO_AUTH",
  LOTTERY_AWARD_AUTH = "LOTTERY_AWARD_AUTH",
  LOTTERY_AWARD_FAKE = "LOTTERY_AWARD_FAKE",
}
